version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # user: "node:1000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
volumes:
  node_modules:
